stages:
  - test
  - validate
  - build
  - deploy infrastructure
  - deploy code

cache:
  paths:
    - .terraform

test:
  stage: test
  image: alpine:latest
  script:
    - "apk update"
    - "apk add yarn"
    - "yarn"
    - "yarn test"

build:
  stage: build
  image: alpine:latest
  script:
    - "apk update"
    - "apk add yarn"
    - "yarn"
    - "yarn build"
  artifacts:
    paths:
      - build

validate:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: validate
  script:
    - "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    - "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY"
    - "export AWS_DEFAULT_REGION=us-east-1"
    - "terraform init -reconfigure -input=false"
    - "terraform workspace select prod || terraform workspace new prod"
    - "terraform validate -input=false -var gitlab_group_id=$GROUP_ID -var api_key=$API_KEY -var aws_user=$AWS_USER"

infrastructure deploy:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: deploy infrastructure
  script:
    - "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    - "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY"
    - "export AWS_DEFAULT_REGION=us-east-1"
    - "terraform init -reconfigure -input=false"
    - "terraform workspace select prod || terraform workspace new prod"
    - "terraform apply -input=false -auto-approve -var gitlab_group_id=$GROUP_ID -var api_key=$API_KEY -var aws_user=$AWS_USER"


prod deploy:
  environment: Production
  image: python:3.7.0b4-alpine3.7
  stage: deploy code
  only:
    - prod
  script:
    - "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    - "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY"
    - "export AWS_DEFAULT_REGION=us-east-1"
    - "pip install awscli"
    - "aws s3 sync ./build s3://www.kpitzen.io"

dev deploy:
  environment: Development
  image: python:3.7.0b4-alpine3.7
  stage: deploy code
  only:
    - master
  script:
    - "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    - "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY"
    - "export AWS_DEFAULT_REGION=us-east-1"
    - "pip install awscli"
    - "aws s3 sync ./build s3://dev.kpitzen.io"
